"""print('one')
print('two')
try:
         print(10/0)
except Division by n zero found:
        print("Division by zero  found")
print('four')
print('five')"""




"""print('one')
print('two')
try:
    print(10/2)
    print("No Exeption")
except zeroDivisionError:
      print("Exception passed")
print('Four')
print('Five')"""

"""try:
    print(10/0)
    print("line 2")
    print("line 3")
    print("No exception")
          
except ZeroDivisionError:
          print("exception passed")
print('four')
print('five')"""          


"""try:
  print(10/0)    
except ZeroDivisionError as z:
    print("exception information",z)"""

"""#try with multiplle except block
try:
    x=int(input("Enter first Number"))
    y=int(input("Enter second Number"))
    print(x/y)
except zeroDivisionError:
    print("cant divide with zero")
except valueerror:
    print("please provide the value")"""


"""try:
    x=int(input("Enter first Number"))
    y=int(input("Enter second Number"))
    print(x/y)
except (zeroDivisionError,ValueError) as e:
     print("please provide the valid numbers only and problem is:",e)"""
    

"""try:
    x=int(input("Enter first Number"))
    y=int(input("Enter second Number"))
    print(x/y)
except:
     print("default Except: please provide valid input only")"""
    
















    
               
          

















